import sys

import pygame

def check_events(ship):
    """Reaction to events generated by pressing a key 
    or a mouse button"""
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            sys.exit()
            
        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_RIGHT:
                #Move the ship to the right
                ship.rect.centerx += 1

def update_screen(game_settings, screen, ship):
    """Update images on the screen and flip to the new screen"""
    #Refresh the screen during each iteration of the loop
    screen.fill(game_settings.bg_color)
    ship.blitme()

    #Display the last modified screen
    pygame.display.flip()
